### ISSUE TITLE
Could not resolve type

### ISSUE THREAD

**Issue by acaliaro** [davidbritch/behaviors#19]
Hi @davidbritch 

I have updated your Package to 1.4.0 and when I run the app to a real Device (Android 4.4)
I have this error

Unhandled Exception:

System.TypeLoadException: Could not resolve type with token 010000cc (from typeref, class/assembly Behaviors.BehaviorPropertiesBase, Behaviors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null). 

Returnig to 1.3.0 all works fine

Alessandro

**Comment by davidbritch** [comment]
Hi @acaliaro 

The issue is that v1.4 of the Behaviors library uses .NET Standard 1.0. To use .NET Standard on Xamarin.Android requires a minimum of Android 7.0 (see the table at https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

Whereas v1.3 of the Behaviors library doesn't use .NET Standard, and hence works on Android 4.4.

Hope this answers your issue.

**Comment by acaliaro** [comment]
Understand thanks
