### ISSUE TITLE
The binary Behaviors.dll is built in debug mode.

### ISSUE THREAD

**Issue by linyute** [davidbritch/behaviors#3]
Hi David, 

I install your Behaviors for Xamarin.Forms 1.1.0 from Nuget.
When I publish my UWP app to Windows App Store, then got an error message:

> Error Found: The debug configuration test detected the following errors:
The binary Behaviors.dll is built in debug mode.

So, I use dotPeek to check the Behaviors.dll properties, in Pdb File property:
> y:\Repos\behaviors\Library\Behaviors\obj\Debug\Behaviors.pdb

Maybe you upload the debug mode dll to Nuget not release?

Thank you, and Sorry for my poor English.
Yute Lin

**Comment by davidbritch** [comment]
I *thought* the previous build was a release mode, but I've no way of checking. Apologies. I'll double-check this for the next build.

**Comment by sharabiania** [comment]
I'm having this issue with the version Latest Stable 1.1.0

**Comment by linyute** [comment]
Hi Sharabiania, 
You can download the source code, and build it in release mode.

**Comment by n3wt0n** [comment]
This issue is still open on the available NuGet 1.1.0 package, why did you close it? 
Can you please update it with a properly working version?

I know that we can rebuild the code, but packages should be  hosted on NuGet when you can use them. If not, you have to update the NuGet description saying something like "Not suitable to be used in production".

PS: shouldn't take longer than 1 minute to just rebuild it and update the Package on repo...

**Comment by davidbritch** [comment]
Republished as a Release build.
