### ISSUE TITLE
Not running while XamlCompilationOptions.Skip (not XamlCompilationOptions.Compile)

### ISSUE THREAD

**Issue by rdeveen** [davidbritch/behaviors#4]
Using the NuGet package v1.1.0 and don't use [assembly: XamlCompilation(XamlCompilationOptions.Compile)] the behaviors doesn't work.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xamarin.Forms.Xaml.XamlParseException: Position 11:8. Type behaviors:InvokeCommandAction not found in xmlns clr-namespace:Behaviors;assembly=Behaviors
   at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode
```

**Comment by davidbritch** [comment]
I've just created a sample and haven't been able to reproduce this problem. I targeted:

- Behaviors.Forms 1.1.0
- Xamarin.Forms 2.3.3.180

I was able to run my sample in the iPhone 6 iOS 10.2 simulator without any problems, both with `XamlCompilationOptions.Compile` and `XamlCompilationOptions.Skip`.

At a guess, the linker had stripped the `Behaviors` types out of your sample. See #1 for more details.

**Comment by lhughey** [comment]
David, I ran into this issue with a Xamarin Forms project that I converted to use NetStandard.  Netstandard XF projects don't include an assemblyInfo.cs file by default, so the XamlCompilationOptions was removed from the project.  Things started working again once I added in the XamlCompilationOptions into an empty assemblyInfo.cs into my Netstandard base project.  

Long story stort:
I also had this issue and users might see it more often as they convert to NetStandard on XF.  However, it is easily fixed by adding XamlCompilationOptions.Compile.

**Comment by jpmock** [comment]
I ran into this exact issue and was driving me crazy.  I had converted my app to .net standard and everything else was working, but I was getting:  _InvokeCommandAction not found in xmlns clr-namespace:Behaviors;assembly=Behaviors_

As Ihughey suggested, I had to do the following to compile the Xaml before run time:

I have to place this above namespace declaration in my App.xaml.cs:

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]

Then, everything works fine.
